doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
        types:
            user_id: App\Shopsy\Users\Infrastructure\Persistence\Doctrine\Types\UserId
            user_first_name: App\Shopsy\Users\Infrastructure\Persistence\Doctrine\Types\UserFirstName
            user_last_name: App\Shopsy\Users\Infrastructure\Persistence\Doctrine\Types\UserLastName
            user_email: App\Shopsy\Users\Infrastructure\Persistence\Doctrine\Types\UserEmail
            user_password: App\Shopsy\Users\Infrastructure\Persistence\Doctrine\Types\UserPassword
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            UserModule:
                type: xml
                dir: '%kernel.project_dir%/src/Shopsy/Users/Infrastructure/Persistence/Doctrine/Mapping'
                is_bundle: false
                prefix: App\Shopsy\Users\Domain\Model
                alias: User
