doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
        types:
            uuid: Ramsey\Uuid\Doctrine\UuidType
            user_id: App\Shopsy\IdentityAccess\Main\Infrastructure\Persistence\Doctrine\Identity\Types\UserId
            user_full_name: App\Shopsy\IdentityAccess\Main\Infrastructure\Persistence\Doctrine\Identity\Types\UserFullName
            user_username: App\Shopsy\IdentityAccess\Main\Infrastructure\Persistence\Doctrine\Identity\Types\UserUsername
            user_email: App\Shopsy\IdentityAccess\Main\Infrastructure\Persistence\Doctrine\Identity\Types\UserEmail
            user_password: App\Shopsy\IdentityAccess\Main\Infrastructure\Persistence\Doctrine\Identity\Types\UserPassword
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            IdentityAccessIdentity:
                type: xml
                dir: '%kernel.project_dir%/src/Shopsy/IdentityAccess/Main/Infrastructure/Persistence/Doctrine/Identity/Mapping'
                is_bundle: false
                prefix: App\Shopsy\IdentityAccess\Main\Domain\Model\Identity
            IdentityAccessAuth:
                type: xml
                dir: '%kernel.project_dir%/src/Shopsy/IdentityAccess/Main/Infrastructure/Persistence/Doctrine/Auth/Mapping'
                is_bundle: false
                prefix: App\Shopsy\IdentityAccess\Main\Domain\Model\Auth