common_controllers:
    resource: ../../src/Common/Infrastructure/Delivery/Symfony/Controller/
    type: annotation

identity_access_controllers:
    resource: ../../src/Shopsy/IdentityAccess/Main/Infrastructure/Delivery/Symfony/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
