parameters:
  # the parameter name is an arbitrary string (the 'app.' prefix is recommended
  # to better differentiate your parameters from Symfony parameters).
  app.resources.common: '%kernel.project_dir%/src/Common'
  app.resources.identity_access: '%kernel.project_dir%/src/Shopsy/IdentityAccess'