
imports:
  - { resource: './parameters.yaml' }
  - { resource: 'shopsy/common.yaml' }
  - { resource: 'shopsy/identity_access.yaml' }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Behat\:
        resource: '../tests/Behat/*'
