# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration

imports:
  - { resource: './parameters.yaml' }
  - { resource: 'shopsy/identity_access.yaml' }

services:

  # Command buses
  App\Common\Application\Bus\CommandBus:
    arguments:
      $transactionalSession: '@App\Common\Infrastructure\Application\Command\TransactionalSession'
  App\Common\Application\Bus\QueryBus: ~

  # Transactional sessions
  App\Common\Infrastructure\Application\Command\DoctrineSession:
    arguments:
      $entityManager: '@doctrine.orm.entity_manager'
  App\Common\Infrastructure\Application\Command\TransactionalSession: '@App\Common\Infrastructure\Application\Command\DoctrineSession'

    # php bin/console config:dump-reference debug
    # php bin/console debug:config debug
    # bin/console swoole:server:run